Repository mash-up-kr/NoWeekend-Android, pull requests merged in 2025-05, with the labels that each got.

#7 [#5] Dokka 플러그인 설정
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/java/DokkaConventionPlugin.kt
  build.gradle.kts
  core/common-android/src/main/java/team/noweekend/core/common/android/extension/Context.kt
  core/navigator/src/main/java/team/noweekend/core/navigator/base/Navigator.kt
  core/navigator/src/main/java/team/noweekend/core/navigator/delegate/HomeNavigationDelegate.kt
  core/navigator/src/main/java/team/noweekend/core/navigator/delegate/di/NavigationDelegateModule.kt
  core/navigator/src/main/java/team/noweekend/core/navigator/extra/ExtraFlag.kt
  feature/home/src/main/java/team/noweekend/feature/home/screen/HomeScreen.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/SampleActivity.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/SampleNavHost.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/navigation/SampleNavigation.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/screen/SampleRoute.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/screen/SampleScreen.kt
  gradle.properties
  gradle/libs.versions.toml
Labels: D-3

#14 [#13] auto-assign workflow 생성
  .github/auto_assign.yml
Labels: D-1

#21 [#8] MVI 리팩터링 : 공통코드 제거 및 제네릭 제한
  core/common-android/src/main/java/team/noweekend/core/common/android/base/MVIViewModel.kt
  core/common-android/src/main/java/team/noweekend/core/common/android/mvi/Intent.kt
  core/common-android/src/main/java/team/noweekend/core/common/android/mvi/SideEffect.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/SampleNavHost.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/detail/mvi/SampleDetailIntent.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/detail/mvi/SampleDetailSideEffect.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/detail/mvi/SampleDetailViewModel.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/detail/navigation/SampleDetailNavigation.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/detail/screen/SampleDetailRoute.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/detail/screen/SampleDetailScreen.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/home/mvi/SampleIntent.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/home/mvi/SampleSideEffect.kt
  feature/sample/src/main/java/team/noweekend/feature/sample/home/mvi/SampleViewModel.kt
Labels: D-0
